spring.application.name=Ex09Model

#thymeleaf
spring.thymeleaf.cache=false

# devtools \uC124\uC815
spring.devtools.restart.enabled = true
spring.devtools.livereload.enabled = true

# \uC11C\uBC84 \uC7AC\uAD6C\uB3D9\uC2DC \uC81C\uC678\uD560 \uACBD\uB85C
spring.devtools.restart.exclude=static/**,templates/**