spring.application.name=Ex16Security01

# thymeleaf
spring.thymeleaf.cache=false

# security
# \uAE30\uBCF8 user.name/password\uB97C \uBD80\uC5EC\uD558\uC5EC \uC811\uADFC \uAC00\uB2A5\uD558\uB3C4\uB85D \uD568
spring.security.user.name=user
spring.security.user.password=1234